### ISSUE TITLE
Also removes import * as React from 'react';

### ISSUE THREAD

**Issue by robbiesmith79** [kcmr/vsce-remove-unused-imports#27]
I get that this is probably bad practice to even use `import * as React from 'react';` but I see this removal as an unintended consequence. I don't think this line should be included in the removal script.

**Comment by kcmr** [comment]
Hi @robbiesmith79 

Yes, there is an open issue about this that I want to fix at some moment.
If you are using the classic JSX runtime, the React import should be preserved but it is not. If you're using the new JSX transform, the import can be safely removed.
I'm going to close this one since it refers to the same issue that #19

Thank you for using the extension.
